### ISSUE TITLE
check lengths of lines to see if rectangle

### ISSUE THREAD

**Issue by Angelchild00** [Angelchild00/CSCN71020_Group8#19]

**Comment by lcy0525** [comment]
I think this part of the requirement is not necessary. Because if the length of four lines are equal, it is square and still one type of rectangle. square belongs to rectangle. And I checked the requirement of prof, this part isn't mentioned. So I think we don't need to do this unnecessary thing.

**Comment by lcy0525** [comment]
We just need to make sure 4 lines are vertical, the angle function.

**Comment by Yunehr** [comment]
luis was correct, it is not needed
